
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'bryanalban39'
    scannerMode: 'MSBuild'
    projectKey: 'bryanalban39'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: CmdLine@2
  inputs:
    script: 'npm run test-ci'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'front'
    publishLocation: 'Container'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'devopsrep'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'devopsrep'
    command: 'push'
