resource_group_name = "reto"
resource_group_location = "South America"
virtual_network_name = "vnetprod019"
subnet_name = "subnet019"
public_ip_name = "publicip019"
network_security_group_name = "nsgprod019"
network_interface_name = "nicprod019"
linux_virtual_machine_name = "linuxvm019"
